### ISSUE TITLE
Java String Reverse - Java

### ISSUE THREAD

**Issue by chaudharypraveen98** [chaudharypraveen98/Competitive-Programming#198]
Please follow the standard coding structure and try to optimize the code as much as possible. Make sure to add comments to make code easily understandable to begineers.<br> URL : https://github.com/chaudharypraveen98/Competitive-Programming/tree/master/Java/Hackerrank/Java%20String%20Reverse

**Comment by chaudharypraveen98** [comment]
@profumato4 Can you close all the Issues which you had completed. I have updated all java readme like [this](https://github.com/chaudharypraveen98/Competitive-Programming/tree/master/Java/Hackerrank/Java%20String%20Reverse). I have extracted all the contents using scraper but make sure to replace **[SVG image]** with relavent content in readme else I will update one I get time.

**Comment by chaudharypraveen98** [comment]
#257

**Comment by profumato4** [comment]
i'll check tomorrow

**Comment by profumato4** [comment]
i'll do something tomorrow night i think

**Comment by profumato4** [comment]
How do I close all Issues

**Comment by profumato4** [comment]
@chaudharypraveen98 check the pr
