### ISSUE TITLE
Variable Sized Arrays - C++

### ISSUE THREAD

**Issue by chaudharypraveen98** [chaudharypraveen98/Competitive-Programming#251]
Please follow the standard coding structure and try to optimize the code as much as possible. Make sure to add comments to make code easily understandable to begineers.<br> URL : https://github.com/chaudharypraveen98/Competitive-Programming/tree/master/C++/Hackerrank/Variable%20Sized%20Arrays

**Comment by heyhimansh** [comment]
`This solution is for c++ lang

#include <iostream>
using namespace std;

int main(int argc, char *argv[]) {
    int n;
    int q;
    cin >> n >> q;
    
    **// Create an array of pointers to integer arrays 
    // (i.e., an array of variable-length arrays)**
    int** outer = new int*[n];

    // Fill each index of 'outer' with a variable-length array
    for(int i = 0; i < n; i++) {
        int k;
        cin >> k;
        // Create an array of length 'k' at index 'i'
        outer[i] = new int[k];

        // Fill each cell in the 'inner' variable-length array
        for(int j = 0; j < k; j++) {
            cin >> outer[i][j];
        }
    }

    // Perform queries:
    while(q-- > 0) {
        int outer_index;
        int inner_index;
        cin >> outer_index >> inner_index;
        
        **// Find the variable-length array located at outer_index
        // and print the value of the element at inner_index.**
        cout << outer[outer_index][inner_index] << endl;
    }

    return 0;
}`

**Comment by chaudharypraveen98** [comment]
Great ...Make a pull request and i will merge the file

**Comment by heyhimansh** [comment]
not able to create a pull request !!

**Comment by chaudharypraveen98** [comment]
First make a fork then you will able to make pr

**Comment by heyhimansh** [comment]
check the pull request
